"""Agent state definition for the Autonomous AI Red Teaming Agent.

This TypedDict defines the shared state passed between all nodes in the LangGraph.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Annotated, Any, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

PHASES = [
    "reconnaissance",
    "scanning",
    "exploitation",
    "post_exploitation",
    "reporting",
]


@dataclass
class Finding:
    """Represents a discovered security finding."""

    target: str
    vulnerability: str
    severity: str  # critical, high, medium, low, info
    port: int | None = None
    service: str | None = None
    evidence: str = ""
    remediation: str = ""
    cve: str | None = None
    exploited: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Convert finding to a dictionary for state storage."""
        return asdict(self)


class AgentState(TypedDict):
    """State schema for the red teaming agent graph.

    All nodes read from and write to this state.
    """

    # Core LangGraph field - conversation history (messages are appended automatically)
    messages: Annotated[list[BaseMessage], add_messages]

    # Red teaming workflow fields
    current_phase: str
    # Valid values: "reconnaissance", "scanning", "exploitation", "post_exploitation", "reporting"

    findings: list[dict[str, Any]]
    # List of Finding objects converted to dicts

    step_count: int
    max_steps: int

    approved_actions: list[str]
    # Track tool calls that required explicit human approval

    allowed_subnet: str
    # Safety guardrail: agent can only target IPs in this subnet

    targets: list[str]
    # List of discovered or provided target IPs/hostnames

    sessions: list[dict[str, Any]]
    # Metasploit sessions or other active connections

    plan: str
    # High-level attack plan generated by the agent

    human_feedback: str
    # Feedback from the operator during HITL approval/denial


def initial_state(
    targets: list[str] | None = None,
    max_steps: int = 50,
    allowed_subnet: str = "172.28.0.0/16"
) -> AgentState:
    """Initialize a fresh agent state."""
    return {
        "messages": [],
        "current_phase": "reconnaissance",
        "findings": [],
        "step_count": 0,
        "max_steps": max_steps,
        "approved_actions": [],
        "allowed_subnet": allowed_subnet,
        "targets": targets or [],
        "sessions": [],
        "plan": "",
        "human_feedback": "",
    }
